<?php

namespace Istic\DemesneBundle\Repository;

/**
 * SSLCertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SSLCertRepository extends \Doctrine\ORM\EntityRepository
{
}
