
Istic\DemesneBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        created_at:
            type: datetime
            nullable: true
            column: createdAt
        modified_at:
            type: datetime
            nullable: true
            column: modifiedAt
    oneToMany:
        domains:
            targetEntity: Domain
            mappedBy: user
        certs:
            targetEntity: SSLCert
            mappedBy: user
    lifecycleCallbacks:
        prePersist: [updatedTimestamps]